name: CI

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      - name: Test
        run: |
          echo $USER:$GROUPS
          echo $PWD
          echo $(curl -fsSL git.io/depends-ubuntu-1804)
